### PR TITLE
LSIF Indexing Campaign

### PR DESCRIPTION
**Pull request by garobrik**
redux

### CODE REVIEW

**Review by efritz — CHANGES_REQUESTED** [review]
Still does not index multi-project

**Comment by gbrik** [comment]
as it turns out, this was the only repo which had this issue. going to fix manually in the morning

**Comment by macraig** [comment]
@gbrik @efritz can this be closed?

**Comment by efritz** [comment]
This doesn't currently work because lsif-tsc has an issue with multi-projects. We can close it, but leaving it opens serves as a good reminder to get this to work once we have the bandwidth.

**Comment by Strum355** [comment]
@efritz am i misremembering that lsif-tsc now works for multi-projects?

**Comment by efritz** [comment]
@Strum355 Could you try running the master version of the indexer and see if it works? If so we can update the args here.

**Comment by Strum355** [comment]
`lsif-tsc -p .` discovered no files. `lsif-tsc **/*.ts` did work

**Pull request closed without merging**
