### PR TITLE
Scope DocumentSelector with baseUri

### LINKED ISSUE #8602: Duplicate type signatures/docs in hover tooltips
Sourcegraph.com/GitHub (Chrome extension)

I've seen this multiple times today, always on GitHub. No idea how to repro, and after refreshing it disappears. The first time I saw them, there were 3x, not just 2x (as you see here).

image

image

### PR DESCRIPTION
**Pull request by felixfbecker**
This is a proper fix for both https://github.com/sourcegraph/sourcegraph/issues/8602 and broken codeintel for root files ([Slack thread](https://sourcegraph.slack.com/archives/CHXHX7XAS/p1583444612193300?thread_ts=1583444599.193000&cid=CHXHX7XAS)).
Codeintel extensions need to be able to scope providers to workspace roots. Doing so in `pattern` does not work, because `minimatch` is not built for working with URIs (in particular it broke for files in the root).

Instead, uses the new `baseUri` introduced in https://github.com/sourcegraph/sourcegraph/pull/8858.

Closes https://github.com/sourcegraph/code-intel-extensions/pull/295.
Fixes sourcegraph/sourcegraph#8602.

### CODE REVIEW

**Comment by efritz** [comment]
Am I correct that publishing this will break all current instances?

**Comment by felixfbecker** [comment]
No, it should not. Current instances will ignore the `baseUri` property. They will just continue to see the double hovers unfortunately until they upgrade to 3.14.

**Comment by efritz** [comment]
But we’re no longer setting pattern so won’t no providers be registered correctly on old instances?

**Comment by felixfbecker** [comment]
But the `pattern` was just `**` before (i.e. all files), and we're still setting `language`. If the language server provided a pattern we're still passing that through (just "unscoped"), but none of our language servers use that afaik.

**Comment by felixfbecker** [comment]
(please sanity check what I'm saying, it's late 😅 )

**Comment by efritz** [comment]
Go to bed I’ll test it later tonight and merge :)

**Comment by efritz** [comment]
I ran this and it works neither with DotCom (#8858 has been merged by now and the site version has a rev after that merge commit) nor with a private instance before the merge.

**Review by efritz — CHANGES_REQUESTED** [review]
Needs more manual testing.

**Comment by felixfbecker** [comment]
I'm very confused. I thought the _Go_ issue were fixed by https://github.com/sourcegraph/code-intel-extensions/pull/292 (the revert), and we only had double hovers now?

**Comment by felixfbecker** [comment]
I found the issue, fix in https://github.com/sourcegraph/sourcegraph/pull/8877. The issue was in the extension host, i.e. the changes in this PR are correct.

Verified that codeintel works:

image

**Review by efritz — APPROVED** [review]

**Pull request merged**
