### PR TITLE
Remove LSP support

### PR DESCRIPTION
**Pull request by efritz**
image

### CODE REVIEW

**Review by olafurpg — APPROVED** [review]
Big 👍 from me. Given this change may impact existing users, should we elaborate on the motivation for this change in the PR? I think it would be helpful to have a written summary of why the LSP support has been replaced with LSIF, even if the summary is just "Read our LSIF blog post $LINK"

**Comment by tjdevries** [comment]
What is the best way to test this PR? I have been reading the code but I'm not sure what a good review looks like for this PR

**Comment by efritz** [comment]
> What is the best way to test this PR? I have been reading the code but I'm not sure what a good review looks like for this PR

Unit tests still pass that are unrelated to LSP, so that's good. I'd plan to test it out on a local instance or Cloud by side loading: https://docs.sourcegraph.com/extensions/authoring/local_development

**Comment by tjdevries** [comment]
Primarily just testing that code intel features still work based on LSIF you're saying? Cross-repo jump, etc?

**Review by macraig — APPROVED** [review]
@efritz we can draft something for the 3.31 release post including a short "Why" and "Will this affect my instance?"

**Comment by efritz** [comment]
https://about.sourcegraph.com/blog/deprecating-lsp/

**Pull request merged**
